services:
  database:
    image: postgres:16
    restart: always
    container_name: wordle_database
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/data/postgres
  database_tests:
      image: postgres:16
      container_name: wordle_database_test
      restart: always
      env_file:
        - .env.test
      ports:
        - 5433:5432
volumes:
  pgdata:
    driver: local
