services:
  database:
    image: bitnami/postgresql
    restart: always
    container_name: wordle_database
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/data/postgres
volumes:
  pgdata:
    driver: local
